apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: conversao-distancia
  namespace: argocd
spec:
  project: default
  source:
    repoURL: 'https://github.com/JhowSSilva/conversao-distancia'
    targetRevision: HEAD
    path: k8s
  destination:
    server: 'https://kubernetes.default.svc'
    namespace: conversao-distancia
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
