name: Build, Test and Push Docker image

on:
  push:
    branches:
      - main

jobs:
  build-test-push:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Get latest git tag
        id: get_tag
        run: |
          TAG=$(git describe --tags --abbrev=0 || echo "latest")
          echo "tag=$TAG" >> $GITHUB_OUTPUT

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Build Docker image (local)
        run: |
          docker build -t jhowssilva/conversao-distancia:${{ steps.get_tag.outputs.tag }} -f src/Dockerfile src

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and push Docker image
        uses: docker/build-push-action@v5
        with:
          context: src
          file: src/Dockerfile
          push: true
          tags: |
            jhowssilva/conversao-distancia:${{ steps.get_tag.outputs.tag }}
            jhowssilva/conversao-distancia:latest
