name: Build and Push Docker Image

on:
  push:
    branches:
      - main
    tags:
      - 'v*'

env:
  DOCKER_IMAGE: jhowssilva/conversao-distancia

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0  # Necessário para git describe
      
      - name: Get version tag
        id: version
        run: |
          if [[ $GITHUB_REF == refs/tags/* ]]; then
            VERSION=${GITHUB_REF#refs/tags/}
          else
            VERSION=$(git describe --tags --always --dirty || echo "latest")
          fi
          echo "version=$VERSION" >> $GITHUB_OUTPUT
          echo "Version: $VERSION"
      
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      
      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      
      - name: Build and push Docker image
        uses: docker/build-push-action@v5
        with:
          context: src
          file: src/Dockerfile
          push: true
          tags: |
            ${{ env.DOCKER_IMAGE }}:${{ steps.version.outputs.version }}
            ${{ env.DOCKER_IMAGE }}:latest
          cache-from: type=gha
          cache-to: type=gha,mode=max
      
      - name: Test Docker image
        run: |
          echo "Testing image pull..."
          docker pull ${{ env.DOCKER_IMAGE }}:${{ steps.version.outputs.version }}
          echo "Testing container startup..."
          docker run --rm ${{ env.DOCKER_IMAGE }}:${{ steps.version.outputs.version }} echo "Container test OK"
          
      - name: Summary
        run: |
          echo "🚀 Docker image built and pushed successfully!"
          echo "📦 Image: ${{ env.DOCKER_IMAGE }}:${{ steps.version.outputs.version }}"
          echo "🔄 ArgoCD will automatically sync and deploy the new version"
